import { Spot } from "@/types/spot";

export const DUMMY_SPOTS: Spot[] = [
  {
    id: "dummy-1",
    name: "El Rincón de Pepe",
    category: "restaurant",
    address: "Calle Mayor 12, Madrid",
    url: "https://elrincondepepe.es",
    tags: ["terraza", "paella", "vistas"],
    lat: 40.4153,
    lng: -3.7074,
    createdAt: new Date().toISOString(),
  },
  {
    id: "dummy-2",
    name: "Café La Mañana",
    category: "coffee",
    address: "Calle Fuencarral 45, Madrid",
    tags: ["tranquilo", "wifi", "desayunos"],
    lat: 40.4244,
    lng: -3.7024,
    createdAt: new Date().toISOString(),
  },
  {
    id: "dummy-3",
    name: "Hotel Palacio Real",
    category: "hotel",
    address: "Gran Vía 50, Madrid",
    url: "https://hotelpalacioreal.com",
    tags: ["spa", "lujo", "céntrico"],
    lat: 40.4196,
    lng: -3.7056,
    createdAt: new Date().toISOString(),
  },
  {
    id: "dummy-4",
    name: "Trattoria Roma",
    category: "restaurant",
    address: "Calle Huertas 8, Madrid",
    tags: ["pasta", "romántico", "italiana"],
    lat: 40.4139,
    lng: -3.6978,
    createdAt: new Date().toISOString(),
  },
  {
    id: "dummy-5",
    name: "Cold Brew Bar",
    category: "coffee",
    address: "Calle Velázquez 22, Madrid",
    tags: ["especialidad", "moderno"],
    lat: 40.4231,
    lng: -3.6887,
    createdAt: new Date().toISOString(),
  },
  {
    id: "dummy-6",
    name: "Librería El Sótano",
    category: "other",
    address: "Calle Atocha 33, Madrid",
    tags: ["segunda mano", "tranquilo"],
    lat: 40.4129,
    lng: -3.7001,
    createdAt: new Date().toISOString(),
  },
  {
    id: "dummy-7",
    name: "Asador El Chuletón",
    category: "restaurant",
    address: "Calle Serrano 98, Madrid",
    tags: ["carne", "tradicional"],
    lat: 40.4283,
    lng: -3.6841,
    createdAt: new Date().toISOString(),
  },
  {
    id: "dummy-8",
    name: "The Corner Hotel",
    category: "hotel",
    address: "Paseo de la Castellana 14, Madrid",
    tags: ["moderno", "desayuno incluido"],
    lat: 40.4312,
    lng: -3.6934,
    createdAt: new Date().toISOString(),
  },
];
